org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=moresnifferflowers

minecraft_version=1.20.1

forge_version=1.20.1-47.1.0
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
quark_id=243121
quark_version=5418252
RCH_id=452834
RCH_version=4690530
jei_version=15.20.0.106
jei_version_range=[15.0.0,16.0.0)

version=1.5.3.2